# Generated by Django 5.0.14 on 2026-03-30 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True, max_length=1024)),
                ('logo_url', models.URLField(blank=True, max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-updated_at'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='sponsors_sp_is_acti_ec0ad0_idx')],
            },
        ),
    ]
