# Generated by Django 5.0.14 on 2026-04-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_sponsor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
