# Generated by Django 5.0.14 on 2026-04-14 21:56
#
# Note: RenameIndex (sponsors_sp_categor_f1b2_idx → …) was removed: production DBs
# imported or created on MySQL may use a different index name than Django 0004 emitted
# on SQLite/dev, which breaks migrate with "Key … doesn't exist".

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0004_partners_page_and_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerspagesettings",
            name="pillars",
            field=models.JSONField(
                default=list,
                help_text='List of {"title": str, "body": str, "icon": "handshake"|"layers"|"sparkles"|"trending-up"}',
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="category",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Section heading on the public page, e.g. "Supplements & health", "Lifestyle".',
                max_length=255,
            ),
        ),
    ]
