# Generated by Django 5.0.14 on 2026-04-19 18:27
#
# MySQL: the auto-generated index name often does not match Django's expected
# `sponsors_sp_categor_f1b2_idx`, so RenameIndex fails with ER_NO_SUCH_INDEX (1176).
# Update project state only; the physical index on (category, sort_order) already
# exists from prior migrations under whatever name MySQL chose.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0006_sponsors_hero_kicker_and_defaults"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name="sponsor",
                    new_name="sponsors_sp_categor_880d67_idx",
                    old_name="sponsors_sp_categor_f1b2_idx",
                ),
            ],
        ),
    ]
