"""
Django settings for Your Enhanced Life (ELP) project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import warnings

import pymysql

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Optional local env file (backend/.env) — keep secrets out of version control.
try:
    from dotenv import load_dotenv

    # utf-8-sig strips a UTF-8 BOM so EMAIL_HOST is not silently empty
    # override=True: values in backend/.env win over pre-set OS/shell env (e.g. stale CONTACT_FORM_TO).
    # Production usually has no .env on disk; use real env vars from the host/orchestrator.
    load_dotenv(BASE_DIR / ".env", encoding="utf-8-sig", override=True)
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

allowed_hosts_raw = os.environ.get("DJANGO_ALLOWED_HOSTS", "*")
ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_raw.split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'content',
    'sponsors',
    'dashboard',
    'mailing',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'elp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'elp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

db_name = (os.environ.get("DB_NAME") or os.environ.get("MYSQL_DATABASE") or "").strip()
if db_name:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': db_name,
            'USER': (
                os.environ.get("DB_USER") or os.environ.get("MYSQL_USER") or ""
            ).strip(),
            'PASSWORD': (
                os.environ.get("DB_PASSWORD") or os.environ.get("MYSQL_PASSWORD") or ""
            ),
            'HOST': (
                os.environ.get("DB_HOST") or os.environ.get("MYSQL_HOST") or "127.0.0.1"
            ).strip(),
            'PORT': (
                os.environ.get("DB_PORT") or os.environ.get("MYSQL_PORT") or "3306"
            ).strip(),
        }
    }
else:
    # Development fallback
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Second connection: legacy SQLite file while default is MySQL (dumpdata / one-off migration).
_sqlite_legacy_raw = (os.environ.get("SQLITE_LEGACY_PATH") or "").strip()
if _sqlite_legacy_raw and db_name:
    _sl_path = Path(_sqlite_legacy_raw)
    if not _sl_path.is_absolute():
        _sl_path = BASE_DIR / _sl_path
    DATABASES["sqlite_legacy"] = {
        **DATABASES["default"],
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(_sl_path.resolve()),
        "USER": "",
        "PASSWORD": "",
        "HOST": "",
        "PORT": "",
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Default first; WordPress import hashers last (verify-only, upgraded on login).
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
    "dashboard.wordpress_hashers.WordPressPhpPassHasher",
    "dashboard.wordpress_hashers.WordPressBcryptHasher",
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", BASE_DIR / "media"))
MEDIA_URL = "/media/"
# Host path ./public/images mounted at /app/public_images in Docker — blog uploads mirror here.
PUBLIC_IMAGES_ROOT = (os.environ.get("PUBLIC_IMAGES_ROOT") or "").strip()

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

_cors_from_env = [o.strip() for o in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()]
# Local Next.js dev: only needed if the *browser* calls Django directly (e.g. NEXT_PUBLIC_* direct API).
# Normal setup: browser → same-origin Next `/api/*` → Django; no CORS. When DEBUG, allow common dev origins.
_cors_dev_defaults = (
    [
        "http://127.0.0.1:3000",
        "http://localhost:3000",
        "http://127.0.0.1:3001",
        "http://localhost:3001",
    ]
    if DEBUG
    else []
)
CORS_ALLOWED_ORIGINS = list(dict.fromkeys(_cors_from_env + _cors_dev_defaults))
DASHBOARD_SERVER_SECRET = (os.environ.get("DASHBOARD_SERVER_SECRET") or "").strip()
DASHBOARD_ALLOW_PUBLIC_REGISTRATION = (
    os.environ.get("DASHBOARD_ALLOW_PUBLIC_REGISTRATION", "1") == "1"
)
# When true, new sign-ups get is_staff (useful in local dev; turn off in production).
DASHBOARD_REGISTER_GRANTS_STAFF = (
    os.environ.get(
        "DASHBOARD_REGISTER_GRANTS_STAFF",
        "1" if os.environ.get("DJANGO_DEBUG", "0") == "1" else "0",
    )
    == "1"
)
# When true (default), only Django superusers may use token login and browser dashboard API.
# Set DASHBOARD_REQUIRES_SUPERUSER=0 to allow any active staff user (legacy).
DASHBOARD_REQUIRES_SUPERUSER = (
    os.environ.get("DASHBOARD_REQUIRES_SUPERUSER", "1") == "1"
)
# When DASHBOARD_REQUIRES_SUPERUSER=1, also allow non-super staff ("manager" role) to use
# admin login and dashboard API. Superusers have full access; managers are limited in app code.
DASHBOARD_ALLOW_STAFF_MANAGERS = (
    os.environ.get("DASHBOARD_ALLOW_STAFF_MANAGERS", "1") == "1"
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Transactional SMTP (backend/.env — Zoho)
# ---------------------------------------------------------------------------
# Used by: contact form, password reset, and other member transactional mail.
# Bulk / newsletter mail uses dashboard SMTP profiles (Dashboard → Email → SMTP servers).
#
# Primary (documented in backend/.env.example): Zoho Mail Australia
#   EMAIL_HOST=smtp.zoho.com.au
#   Port 587 + STARTTLS: EMAIL_PORT=587  EMAIL_USE_TLS=1  EMAIL_USE_SSL=0
#   Port 465 + SSL:       EMAIL_PORT=465  EMAIL_USE_TLS=0  EMAIL_USE_SSL=1
#   Require authentication: set EMAIL_HOST_USER / EMAIL_HOST_PASSWORD (mailbox or app password).
#
# Secondary (optional; commented in .env.example): Elastic Email
#   smtp.elasticemail.com, port 2525 + STARTTLS: EMAIL_USE_TLS=1  EMAIL_USE_SSL=0
#
# Set variables in the process environment or in backend/.env (see backend/.env.example).
# If EMAIL_HOST is unset, use the console backend (prints mail to the runserver terminal).
# Do not default to SMTP against localhost — that causes connection refused and HTTP 500s.


def _env_unquoted(key: str) -> str:
    """Strip one layer of matching quotes (common in .env files)."""
    val = (os.environ.get(key) or "").strip()
    if len(val) >= 2 and val[0] == val[-1] and val[0] in ('"', "'"):
        return val[1:-1]
    return val


_email_host = _env_unquoted("EMAIL_HOST")
_explicit_email_backend = _env_unquoted("EMAIL_BACKEND")
if _explicit_email_backend:
    EMAIL_BACKEND = _explicit_email_backend
elif not _email_host:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = _email_host or "localhost"
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = _env_unquoted("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = _env_unquoted("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "1") == "1"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "0") == "1"
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "30"))
DEFAULT_FROM_EMAIL = (os.environ.get("DEFAULT_FROM_EMAIL") or "admin@yourenhancedlife.com").strip()
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# Inbox for website contact form submissions (see mailing.contact_views).
CONTACT_FORM_TO = (os.environ.get("CONTACT_FORM_TO") or "").strip()
# Used in unsubscribe links in outbound mail (no trailing slash).
PUBLIC_SITE_BASE_URL = (os.environ.get("PUBLIC_SITE_BASE_URL") or "http://127.0.0.1:3000").strip().rstrip("/")
# Member password reset emails link to {PUBLIC_SITE_BASE_URL}/reset-password?uid=...&token=...
MEMBER_PASSWORD_RESET_EMAIL_SUBJECT = (
    os.environ.get("MEMBER_PASSWORD_RESET_EMAIL_SUBJECT") or "Reset your password — Your Enhanced Life"
).strip()
# When 1 (default), also email unknown addresses (and staff/superuser) a short notice so SMTP can be tested.
PASSWORD_RESET_SEND_PROBE_FOR_UNKNOWN = (
    os.environ.get("PASSWORD_RESET_SEND_PROBE_FOR_UNKNOWN", "1") == "1"
)

if EMAIL_BACKEND == "django.core.mail.backends.console.EmailBackend":
    msg = (
        "EMAIL_HOST is unset: Django is using the console email backend, so nothing is sent over SMTP. "
        "Set EMAIL_* in the process environment or backend/.env. "
        "If you use Docker, pass variables in the root .env (not backend/.env)."
    )
    if not DEBUG:
        import logging

        logging.getLogger(__name__).error(msg)
    warnings.warn(msg, RuntimeWarning, stacklevel=1)
