# Generated by Django 5.0.14 on 2026-04-02 19:52

from django.db import migrations, models


def mark_default_faq_slug(apps, schema_editor):
    LandingPage = apps.get_model("content", "LandingPage")
    LandingPage.objects.filter(slug="faq").update(is_faq=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='is_faq',
            field=models.BooleanField(default=False, help_text='When true, listed on the public /faq hub and manageable as FAQ content.'),
        ),
        migrations.RunPython(mark_default_faq_slug, noop_reverse),
    ]
