# Generated by Django 5.0.14 on 2026-04-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_seed_public_landing_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='faq_nav_group',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Empty = not in sponsor submenu. 'sponsors' = listed under Sponsors' FAQ in the header.", max_length=32),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq_nav_label',
            field=models.CharField(blank=True, default='', help_text='Label in the FAQ menu (defaults to title).', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq_nav_order',
            field=models.IntegerField(default=0),
        ),
    ]
