# Generated by Django 5.0.14 on 2026-04-02 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_seed_dashboard_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmessage',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='If set, only this user sees the notification; if empty, all staff see it.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DashboardNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_product_updates', models.BooleanField(default=True)),
                ('email_security_alerts', models.BooleanField(default=True)),
                ('browser_push', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
