# Generated by Django 5.0.14 on 2026-04-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auth_messaging_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardconversation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
