# Generated by Django 5.0.14 on 2026-05-30 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('category', models.CharField(default='General', max_length=64)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=5)),
                ('image_url', models.CharField(default='/images/article-default.jpg', help_text='Path or URL for the card hero image (e.g. /images/article-estradiol.jpg).', max_length=512)),
                ('body', models.TextField(blank=True, default='', help_text='HTML body shown on the article page (inside the member gate).')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False, help_text='When true, shown on the main /blog grid (up to 6, by sort order and date).')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', 'sort_order'],
                'indexes': [models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'), models.Index(fields=['is_published', 'is_featured', '-published_at'], name='blog_blogpo_is_publ_bb6f6b_idx')],
            },
        ),
    ]
