# Generated by Django 5.0.14 on 2026-04-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_outbound_email_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outboundemaillog',
            new_name='mailing_out_created_6f5d79_idx',
            old_name='mailing_out_created_0a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='outboundemaillog',
            new_name='mailing_out_created_61b84d_idx',
            old_name='mailing_out_created_0d3e4f_idx',
        ),
    ]
